# Generated by Django 4.0.3 on 2022-09-01 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polyapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialist4',
            new_name='Specialist',
        ),
        migrations.DeleteModel(
            name='Specialist1',
        ),
        migrations.DeleteModel(
            name='Specialist2',
        ),
        migrations.DeleteModel(
            name='Specialist3',
        ),
        migrations.DeleteModel(
            name='Specialist5',
        ),
    ]
