# Generated by Django 4.0.3 on 2023-02-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polyapps', '0002_rename_specialist4_specialist_delete_specialist1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.TextField(max_length=12),
        ),
    ]
